import{S as g,i as L,a as b}from"./assets/vendor-da186403.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const h=15,v="42335875-35ce8b2853e0e3d6760ada5fc",w=`https://pixabay.com/api/?key=${v}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${h}`,S=document.querySelector(".js-search-form"),i=document.querySelector(".js-gallery"),u=document.querySelector(".load-more"),f=document.querySelector(".loader");let c=1,m=null,l=1,p=new g(".gallery a");function d(r){L.show({message:r,messageColor:"#fff",position:"topRight",backgroundColor:"#ef4040",animateInside:!1,color:"#fff"})}async function y(r,o){let n="";try{const a=`${w}&q=${encodeURIComponent(r)}&page=${o}`,t=(await b.get(a)).data;if(!t||t.hits.length===0)return d("Sorry, there are no images matching your search query. Please try again!"),i.innerHTML="",l=0,"";l=Math.ceil(t.totalHits/h),n=t.hits.map(s=>`<a href="${s.largeImageURL}">
                <img src="${s.webformatURL}">
                <div>
                    <span>likes<br>${s.likes}</span>
                    <span>views<br>${s.views}</span>
                    <span>comments<br>${s.comments}</span>
                    <span>downloads<br>${s.downloads}</span>
                </div>
            </a>`).join("")}catch(a){d(a.message),i.innerHTML=""}return n}function q(){const r=document.querySelectorAll(".gallery a"),o=r.length>0?r[0].getBoundingClientRect().height:0;window.scrollBy({top:o*2,behavior:"smooth"})}S.addEventListener("submit",async r=>{r.preventDefault();const n=new FormData(r.target).get("search-input").trim();if(c=1,l=0,!n){d("Sorry, there are no images matching your search query. Please try again!"),i.innerHTML="",m=null;return}f.classList.remove("hidden"),m=n;const a=await y(n,c);i.innerHTML=a,p.refresh(),f.classList.add("hidden"),l>1?u.classList.remove("hidden"):u.classList.add("hidden")});u.addEventListener("click",async r=>{if(r.preventDefault(),!m){d("Sorry, there are no images matching your search query. Please try again!"),i.innerHTML="";return}if(f.classList.remove("hidden"),c<l){c+=1;const o=await y(m,c);i.innerHTML+=o,p.refresh(),q()}else d("We're sorry, but you've reached the end of search results."),u.classList.add("hidden");f.classList.add("hidden")});
//# sourceMappingURL=commonHelpers.js.map
